name: FavShop CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  compose-validate:
    name: Validate Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config